FROM python
WORKDIR /app
COPY . /app
CMD [ "python", "bmi.py" ]


#docker build .
#docker run imageId
#docker tag oldeImageName newImageName -- Change imageName
#docker run -it imageId
#docker run -it --name containerName imageName
#docker run --rm imageId -- run docker container & remove container automatically when it stop
#docker start -a -i containerId